import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Hiring Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen max-w-vw-100 flex items-center justify-center min-h-screen" suppressHydrationWarning>
      <body className="w-full h-screen">
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
